# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.CharField(max_length=32)),
                ('book_id', models.CharField(max_length=32)),
                ('book_name', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('id', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('floor', models.CharField(max_length=32)),
                ('shelf', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=32)),
                ('price', models.CharField(max_length=32)),
                ('ISBN', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=32)),
                ('islent', models.CharField(default='0', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='default',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.CharField(max_length=32)),
                ('return_period', models.CharField(max_length=32)),
                ('deposit', models.CharField(max_length=32)),
                ('post', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='delete',
            fields=[
                ('book_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=32)),
                ('librarian_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=32)),
                ('deposit', models.CharField(max_length=32)),
                ('fine', models.CharField(max_length=32)),
                ('sum', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='lend',
            fields=[
                ('list_id', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('book_id', models.CharField(max_length=32)),
                ('book_name', models.CharField(max_length=32)),
                ('reader_id', models.CharField(max_length=32)),
                ('remain_lendingtime', models.CharField(default='0', max_length=32)),
                ('isreturned', models.CharField(default='0', max_length=32)),
                ('date', models.CharField(max_length=32)),
                ('ispayed', models.CharField(default='0', max_length=32)),
                ('topay_fine', models.CharField(default='0', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='librarian',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pwd', models.CharField(default='00010001', max_length=32)),
                ('isrequest', models.CharField(default='0', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pwd', models.CharField(default='12345678', max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('deposit', models.CharField(max_length=32)),
                ('fine', models.CharField(default='0', max_length=32)),
            ],
        ),
    ]
