# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0002_delete_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pwd', models.CharField(default='12345678', max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('sex', models.CharField(max_length=32)),
                ('deposit', models.CharField(max_length=32)),
                ('fine', models.CharField(default='0', max_length=32)),
            ],
        ),
    ]
