# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0003_reader'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='upload')),
                ('img_name', models.CharField(default='pic_default', max_length=20)),
            ],
        ),
    ]
