# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0004_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='librarian',
        ),
    ]
