# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0005_delete_librarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='librarian',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pwd', models.CharField(default='00010001', max_length=32)),
                ('isrequest', models.CharField(default='0', max_length=32)),
            ],
        ),
    ]
