# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0008_auto_20181111_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(default='noname', upload_to='upload'),
        ),
    ]
