# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0009_auto_20181111_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
