# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0010_auto_20181111_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
