# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0011_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', tinymce.models.HTMLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='default',
            name='post',
        ),
    ]
