# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0012_auto_20181111_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='none', max_length=32),
        ),
    ]
