# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0014_auto_20181112_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='posttext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=32)),
                ('content', tinymce.models.HTMLField()),
                ('timestamp', models.DateTimeField(blank=True, default='2018-11-12', null=True)),
                ('auth', models.TextField(default='mocceli')),
                ('address', models.CharField(default='xian', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
