# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bibliosoft', '0016_auto_20181113_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttext',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='posttext',
            name='date',
            field=models.CharField(default='', max_length=32),
        ),
    ]
